SELECT TOP (1000) [column1]
      ,[column2]
      ,[column3]
      ,[column4]
      ,[column5]
      ,[column6]
      ,[column7]
      ,[column8]
      ,[column9]
      ,[column10]
  FROM [master].[db_owner].[Sample-Spreadsheet-100-rows]